/**
 * Registro central de iconos (Lucide via react-icons: trazo simple, minimalista).
 *
 * Regla del proyecto: los componentes NO importan de 'react-icons' directamente,
 * importan de aqui. Asi el set de iconos se cambia en un solo archivo.
 */
import {
  LuArchive,
  LuArrowLeft,
  LuBell,
  LuBookOpen,
  LuCalendar,
  LuCamera,
  LuCheck,
  LuCheckCheck,
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuChevronUp,
  LuCircleAlert,
  LuCircleCheck,
  LuCircleHelp,
  LuClipboardList,
  LuClock,
  LuCopy,
  LuEllipsisVertical,
  LuExternalLink,
  LuFile,
  LuFileText,
  LuFolder,
  LuHouse,
  LuImage,
  LuKeyRound,
  LuLink,
  LuListChecks,
  LuLock,
  LuLoaderCircle,
  LuLogOut,
  LuMail,
  LuMenu,
  LuMessageSquare,
  LuMonitor,
  LuMoon,
  LuPalette,
  LuPaperclip,
  LuPencil,
  LuPhone,
  LuPlus,
  LuPower,
  LuSearch,
  LuShieldCheck,
  LuSun,
  LuSend,
  LuSettings,
  LuRotateCcw,
  LuSquareCheckBig,
  LuTrash2,
  LuTrendingUp,
  LuTriangleAlert,
  LuUpload,
  LuUser,
  LuUserPlus,
  LuUsers,
  LuVideo,
  LuX,
} from 'react-icons/lu'

export const Icon = {
  // Navegacion
  menu: LuMenu,
  home: LuHouse,
  calendar: LuCalendar,
  bell: LuBell,
  settings: LuSettings,
  archive: LuArchive,
  back: LuArrowLeft,
  chevronLeft: LuChevronLeft,
  chevronRight: LuChevronRight,
  chevronDown: LuChevronDown,
  chevronUp: LuChevronUp,
  close: LuX,
  search: LuSearch,
  logout: LuLogOut,

  // Cursos y trabajo en clase
  course: LuBookOpen,
  classwork: LuClipboardList,
  assignment: LuFileText,
  material: LuFile,
  question: LuCircleHelp,
  quiz: LuListChecks,
  topic: LuFolder,
  grades: LuSquareCheckBig,

  // Personas y cuenta
  user: LuUser,
  people: LuUsers,
  invite: LuUserPlus,
  admin: LuShieldCheck,
  key: LuKeyRound,
  lock: LuLock,
  power: LuPower,
  mail: LuMail,
  phone: LuPhone,

  // Acciones
  add: LuPlus,
  edit: LuPencil,
  delete: LuTrash2,
  copy: LuCopy,
  send: LuSend,
  attach: LuPaperclip,
  link: LuLink,
  inviteLink: LuExternalLink,
  video: LuVideo,
  comment: LuMessageSquare,
  more: LuEllipsisVertical,
  restore: LuRotateCcw,
  progress: LuTrendingUp,
  upload: LuUpload,
  camera: LuCamera,
  image: LuImage,
  palette: LuPalette,

  // Tema claro / oscuro
  light: LuSun,
  dark: LuMoon,
  system: LuMonitor,

  // Estados
  check: LuCheck,
  checkAll: LuCheckCheck,
  success: LuCircleCheck,
  warning: LuTriangleAlert,
  error: LuCircleAlert,
  clock: LuClock,
  spinner: LuLoaderCircle,
} as const

export type IconName = keyof typeof Icon
